SUPABASE_URL = "https://nmmmaffnywafmohvwdiw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbW1hZmZueXdhZm1vaHZ3ZGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE1NTAyMzQsImV4cCI6MjAxNzEyNjIzNH0.bzeKXqZ4P9ADiaLWg6Or3FGC7IC_GmKZp-tvuSfSQF4"
